wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.30.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1706272388.59263
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 71
      - 103
      3:
      - 13
      - 23
      4: 3.11.0
      5: 0.16.2
      6: 4.30.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
