wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.0
    cli_version: 0.16.2
    framework: huggingface
    huggingface_version: 4.30.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1706272375.871523
    t:
      1:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 71
      - 103
      2:
      - 1
      - 5
      - 9
      - 11
      - 41
      - 49
      - 53
      - 55
      - 71
      - 103
      3:
      - 2
      - 7
      - 13
      - 23
      4: 3.11.0
      5: 0.16.2
      6: 4.30.0
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: trainer/global_step
      6:
      - 3
emotion_output_dim:
  desc: null
  value: 7
trigger_output_dim:
  desc: null
  value: 2
freeze_bert:
  desc: null
  value: true
bert_model_name:
  desc: null
  value: bert-base-uncased
use_encoder_cache:
  desc: null
  value: true
encoder_cache_size:
  desc: null
  value: 100000
lr:
  desc: null
  value: 0.001
class_weights_emotion:
  desc: null
  value:
  - 1.3134828805923462
  - 4.869222640991211
  - 4.3329176902771
  - 0.7755779027938843
  - 0.32493340969085693
  - 2.0597643852233887
  - 1.0525259971618652
class_weights_trigger:
  desc: null
  value:
  - 0.5911622047424316
  - 3.2423641681671143
hidden_layers:
  desc: null
  value: 2
dropout:
  desc: null
  value: 0.2
